-- MySQL Workbench Synchronization
-- Generated: 2019-01-30 11:39
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Floris

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `sitesubnets` 
ADD COLUMN `mdnsrepeater` TINYINT(1) NULL DEFAULT NULL AFTER `dnsredirect`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
